version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: localhost
      POSTGRES_USER: postgres
      POSTGRES_DB: elmolino
    ports:
      - '5433:5432'
